version: '3.4'

services:
  service1:
    image: first_server
    build:
      context: .
    ports:
    - 0.0.0.0:3000:3000
    networks:
    - my-network
  service2:
    image: first_server
    build:
      context: .
    ports:
    - 0.0.0.0:3030:3000
    networks:
    - my-network
  service3:
    image: first_server
    build:
      context: .
    ports:
    - 0.0.0.0:5000:3000
    networks:
    - my-network
      
networks:
  my-network:
    external: true