version: '3.4'

services:
  service1:
    image: first_server
    hostname: service1
    ports:
    - 3000:3000
    networks:
    - my-network
  service2:
    image: first_server
    hostname: service2
    ports:
    - 3030:3000
    networks:
    - my-network
  service3:
    image: first_server   
    hostname: service3
    ports:
    - 5000:3000
    networks:
    - my-network

networks:
  my-network:
    external: true